services:
  LuxuryHomeAbidjan-Production:
    env_file:
      - .env
    build:
      context: .
      args:
        NEXT_PUBLIC_CDN_URL: ${NEXT_PUBLIC_CDN_URL}
        NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: ${NEXT_PUBLIC_EMAILJS_PUBLIC_KEY}
        NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${NEXT_PUBLIC_EMAILJS_SERVICE_ID}
    image: luxury-home-abidjan-production
    ports:
      - "${DOCKER_PORT}:3000"