import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/home/navbar/navbar";
import Footer from "../components/home/footer/footer";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Montserrat,Noto_Serif, } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const noto = Noto_Serif({
  variable: "--font-noto",
  subsets: ["latin"],
});
const montserrat =Montserrat({
   variable: "--font-geist-montserrat",
    subsets: ["latin"],
})
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${noto.variable} ${montserrat.variable} antialiased`}
      >
        <NuqsAdapter>
          <main className="font-montserrat mx-auto">
            {children}
            <Footer />
          </main>
          <Toaster />
        </NuqsAdapter>
      </body>
    </html>
  );
}